
export const GET_CATEGORIES = 'GET_CATEGORIES'
export const SELECT_CATEGORY = 'SELECT_CATEGORY'
export const GET_POST = 'GET_POST'
export const GET_NEW_POST = 'GET_NEW_POST'
export const DELETE_POST = 'DELETE_POST'
export const VOTE = 'VOTE'
export const GET_POSTS = 'GET_POSTS'
export const GET_POST_COMMENTS = 'GET_POST_COMMENTS'
export const GET_COMMENT = 'GET_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const SET_SORT = 'SET_SORT'